IPs:
  node0: 47.87.128.237
  node1: 47.245.151.110
  node2: 8.208.86.221
  node3: 8.208.71.89
  node4: 47.236.38.180
  node5: 47.237.93.237
  node6: 8.220.210.16
p2p_ports:
  node0: 9000
  node1: 9000
  node2: 9000
  node3: 9000
  node4: 9000
  node5: 9000
  node6: 9000
max_pool: 64
log_level: 3
batch_size: 200
tx_size: 250
round: 12
faulty_number: 2
protocol: wahoo
