IPs:
  node0: 47.87.129.122
  node1: 47.245.151.44
  node2: 47.245.150.132
  node3: 47.87.129.173
p2p_port: 9000
max_pool: 31
log_level: 3
batch_size: 500
round: 20
faulty_number: 0
protocol: wahoo
tx_size: 250
