IPs:
  node0: 47.87.128.237
  node1: 47.87.129.92
  node2: 8.208.71.89
  node3: 8.208.71.44
  node4: 47.84.13.232
  node5: 47.84.17.165
  node6: 8.220.210.16
p2p_ports:
  node0: 9000
  node1: 9000
  node2: 9000
  node3: 9000
  node4: 9000
  node5: 9000
  node6: 9000
max_pool: 64
log_level: 3
batch_size: 5000
tx_size: 250
round: 15
faulty_number: 2
protocol: tusk
