IPs:
  node0: 47.87.129.92
  node1: 47.87.132.216
  node2: 8.208.87.162
  node3: 8.208.86.221
p2p_ports:
  node0: 9000
  node1: 9000
  node2: 9000
  node3: 9000
max_pool: 64
log_level: 3
batch_size: 100
tx_size: 250
round: 15
faulty_number: 0
protocol: wahoo
