IPs:
  node0: 47.87.128.146
  node1: 47.245.150.174
  node2: 47.245.148.171
  node3: 47.87.128.85
p2p_port: 9000
max_pool: 31
log_level: 3
batch_size: 500
round: 20
faulty_number: 0
protocol: wahoo
tx_size: 250
