- hosts: BFT
  remote_user: root
  tasks:
    - name: copy configuration file
      copy:
        src: /home/gzx/gitrepo/Wahoo/config_gen/{{inventory_hostname}}_{{item}}.yaml
        dest: /root/BFT{{item}}/config.yaml
      loop:
        - 0
      when: ansible_hostname is not match "node0"

    - name: copy configuration file
      copy:
        src: /home/gzx/gitrepo/Wahoo/config_gen/{{inventory_hostname}}_{{item}}.yaml
        dest: /root/BFT{{item}}/config.yaml
      loop:
        - 0
      when: (ansible_hostname is match "node0")

